language: ruby
dist: trusty
cache: bundler
bundler_args: --without development
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
  - sh -e /etc/init.d/xvfb start
  - bin/rake refinery:testing:dummy_app
  - export DISPLAY=:99.0
env:
  - DB=postgresql
  - DB=mysql
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/b5d48907cdc89864b874
rvm:
  - 2.6.4
  - 2.5.6
  - 2.4.7
sudo: false
