language: ruby
cache: bundler
bundler_args: --without development
before_script:
  - sh -e /etc/init.d/xvfb start
  - bin/rake refinery:testing:dummy_app
  - export DISPLAY=:99.0
env:
  - DB=postgresql
  - DB=mysql
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/b5d48907cdc89864b874
rvm:
  - 2.4.1
  - 2.3.3
  - 2.2.6
sudo: false
